# Generated by Django 4.1.7 on 2023-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=30)),
                ('relevant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='static/images')),
                ('deploy_link', models.URLField(blank=True, unique=True)),
                ('github_link', models.URLField(blank=True, unique=True)),
                ('youtube_link', models.URLField(blank=True, unique=True)),
                ('about', models.TextField()),
                ('category', models.ManyToManyField(to='model.skills')),
            ],
        ),
    ]
