# Generated by Django 4.1.7 on 2023-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='youtube_link',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
