# Generated by Django 4.1.7 on 2023-03-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_projects_skills_delete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.skills'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
