# Generated by Django 4.1.7 on 2023-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_projects_category_alter_projects_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
    ]
